export const ROUTES = {
  home: "/",
  termux: "/termux",
  termuxApi: "/termux/api",
  karnel: "/karnel",
  ai: "/karnel/ai",
  osint: "/karnel/osint",
  editor: "/karnel/editor",
  deploy: "/karnel/deploy",
  doctor: "/karnel/doctor",
  show: "/karnel/show",
  linux: "/karnel/linux",
  brain: "/karnel/brain",
  voice: "/karnel/voice",
  pg: "/karnel/pg",
  init: "/karnel/init",
  env: "/karnel/env",
  lang: "/karnel/lang",
  db: "/karnel/db",
  dev: "/karnel/dev",
  npm: "/karnel/npm",
  shell: "/karnel/shell",
  ui: "/karnel/ui",
  auto: "/karnel/auto",
  games: "/karnel/games",
  network: "/karnel/network",
  utils: "/karnel/utils",
  cleanup: "/karnel/cleanup",
  backup: "/karnel/backup",
  terms: "/terms",
  notFound: "/404",
} as const;

export const ROUTE_PATHS = Object.values(ROUTES);

export const DOCUMENTATION_NAV = [
  { label: "Termux", href: ROUTES.termux },
  { label: "Termux:API", href: ROUTES.termuxApi },
  { label: "Karnel", href: ROUTES.karnel },
  { label: "AI Tools", href: ROUTES.ai },
  { label: "OSINT / Robin", href: ROUTES.osint },
  { label: "Languages", href: ROUTES.lang },
  { label: "Databases", href: ROUTES.db },
  { label: "Editor", href: ROUTES.editor },
  { label: "Dev Tools", href: ROUTES.dev },
  { label: "npm", href: ROUTES.npm },
  { label: "Shell", href: ROUTES.shell },
  { label: "UI", href: ROUTES.ui },
  { label: "Auto", href: ROUTES.auto },
  { label: "Games", href: ROUTES.games },
  { label: "Network", href: ROUTES.network },
  { label: "Utils", href: ROUTES.utils },
  { label: "Linux Stack", href: ROUTES.linux },
  { label: "Second Brain", href: ROUTES.brain },
  { label: "Voice", href: ROUTES.voice },
  { label: "PG", href: ROUTES.pg },
  { label: "Init", href: ROUTES.init },
  { label: "Env", href: ROUTES.env },
  { label: "Deploy", href: ROUTES.deploy },
  { label: "Cleanup", href: ROUTES.cleanup },
  { label: "Doctor", href: ROUTES.doctor },
  { label: "Show", href: ROUTES.show },
  { label: "Backup", href: ROUTES.backup },
] as const;
