// Auto-generated by scripts/generate-catalog.mjs
// DO NOT EDIT — source of truth is karnel-termux CLI registries.
// Run: node scripts/generate-catalog.mjs

export const AI_TOOLS = [
  {
    name: "10Router",
    flag: "--10router",
    desc: "10Router managed through the Karnel ai_tools module.",
  },
  {
    name: "Qwen Code",
    flag: "--qwen-code",
    desc: "Qwen Code managed through the Karnel ai_tools module.",
  },
  {
    name: "Gemini CLI",
    flag: "--gemini-cli",
    desc: "Gemini CLI managed through the Karnel ai_tools module.",
  },
  {
    name: "Claude Code",
    flag: "--claude-code",
    desc: "Claude Code managed through the Karnel ai_tools module.",
  },
  {
    name: "Mistral Vibe",
    flag: "--mistral-vibe",
    desc: "Mistral Vibe managed through the Karnel ai_tools module.",
  },
  {
    name: "OpenClaude",
    flag: "--openclaude",
    desc: "OpenClaude managed through the Karnel ai_tools module.",
  },
  {
    name: "OpenClaw",
    flag: "--openclaw",
    desc: "OpenClaw managed through the Karnel ai_tools module.",
  },
  {
    name: "Ollama",
    flag: "--ollama",
    desc: "Ollama managed through the Karnel ai_tools module.",
  },
  {
    name: "Codex CLI",
    flag: "--codex",
    desc: "Codex CLI managed through the Karnel ai_tools module.",
  },
  {
    name: "OpenCode",
    flag: "--opencode",
    desc: "OpenCode managed through the Karnel ai_tools module.",
  },
  {
    name: "MiMo Code",
    flag: "--mimocode",
    desc: "MiMo Code managed through the Karnel ai_tools module.",
  },
  {
    name: "Engram",
    flag: "--engram",
    desc: "Engram managed through the Karnel ai_tools module.",
  },
  {
    name: "CodeGraph",
    flag: "--codegraph",
    desc: "CodeGraph managed through the Karnel ai_tools module.",
  },
  {
    name: "Pi Coding Agent",
    flag: "--pi",
    desc: "Pi Coding Agent managed through the Karnel ai_tools module.",
  },
  {
    name: "Antigravity CLI",
    flag: "--antigravity-cli",
    desc: "Antigravity CLI managed through the Karnel ai_tools module.",
  },
  {
    name: "Minimax CLI",
    flag: "--minimax-cli",
    desc: "Minimax CLI managed through the Karnel ai_tools module.",
  },
  {
    name: "Gentle AI",
    flag: "--gentle-ai",
    desc: "Gentle AI managed through the Karnel ai_tools module.",
  },
  {
    name: "GGA",
    flag: "--gga",
    desc: "GGA managed through the Karnel ai_tools module.",
  },
  {
    name: "Hermes Agent",
    flag: "--hermes-agent",
    desc: "Hermes Agent managed through the Karnel ai_tools module.",
  },
  {
    name: "Kimi Code",
    flag: "--kimi-code",
    desc: "Kimi Code managed through the Karnel ai_tools module.",
  },
  {
    name: "Command Code",
    flag: "--command-code",
    desc: "Command Code managed through the Karnel ai_tools module.",
  },
  {
    name: "Codebuff",
    flag: "--codebuff",
    desc: "Codebuff managed through the Karnel ai_tools module.",
  },
  {
    name: "Freebuff",
    flag: "--freebuff",
    desc: "Freebuff managed through the Karnel ai_tools module.",
  },
  {
    name: "Kilo Code CLI",
    flag: "--kilocode-cli",
    desc: "Kilo Code CLI managed through the Karnel ai_tools module.",
  },
  {
    name: "Kiro CLI",
    flag: "--kiro",
    desc: "Kiro CLI managed through the Karnel ai_tools module.",
  },
  {
    name: "Crush CLI",
    flag: "--crush",
    desc: "Crush CLI managed through the Karnel ai_tools module.",
  },
  {
    name: "Cline CLI",
    flag: "--cline",
    desc: "Cline CLI managed through the Karnel ai_tools module.",
  },
  {
    name: "Odysseus",
    flag: "--odysseus",
    desc: "Odysseus managed through the Karnel ai_tools module.",
  },
  {
    name: "Kimchi CLI",
    flag: "--kimchi-code",
    desc: "Kimchi CLI managed through the Karnel ai_tools module.",
  },
  {
    name: "omniRoute",
    flag: "--omni-route",
    desc: "omniRoute managed through the Karnel ai_tools module.",
  },
  {
    name: "Context7 Documentation Provider",
    flag: "--ctx7",
    desc: "Context7 Documentation Provider managed through the Karnel ai_tools module.",
  },
  {
    name: "OpenSpec SDD Framework",
    flag: "--openspec",
    desc: "OpenSpec SDD Framework managed through the Karnel ai_tools module.",
  },
  {
    name: "Supercode CLI",
    flag: "--supercode-cli",
    desc: "Supercode CLI managed through the Karnel ai_tools module.",
  },
  {
    name: "Puter CLI",
    flag: "--puter",
    desc: "Puter CLI managed through the Karnel ai_tools module.",
  },
  { name: "KeelCode", flag: "--keelcode", desc: "Hosted coding-agent CLI" },
  {
    name: "Copilot-Termux",
    flag: "--copilot-termux",
    desc: "Copilot-Termux managed through the Karnel ai_tools module.",
  },
  {
    name: "Qoder",
    flag: "--qoder",
    desc: "Qoder managed through the Karnel ai_tools module.",
  },
  {
    name: "AMP Code CLI",
    flag: "--ampcode",
    desc: "AMP Code CLI managed through the Karnel ai_tools module.",
  },
  {
    name: "Cursor CLI",
    flag: "--cursor-cli",
    desc: "Cursor CLI managed through the Karnel ai_tools module.",
  },
  {
    name: "Oh-My-Pi",
    flag: "--oh-my-pi",
    desc: "Oh-My-Pi managed through the Karnel ai_tools module.",
  },
  {
    name: "Goose CLI",
    flag: "--goose",
    desc: "Goose CLI managed through the Karnel ai_tools module.",
  },
  {
    name: "Factory Droid",
    flag: "--droid",
    desc: "Factory Droid managed through the Karnel ai_tools module.",
  },
  {
    name: "Cactus",
    flag: "--cactus",
    desc: "Cactus managed through the Karnel ai_tools module.",
  },
  {
    name: "Cactus Needle",
    flag: "--cactus-needle",
    desc: "Cactus Needle managed through the Karnel ai_tools module.",
  },
  {
    name: "Walkie Agent",
    flag: "--walkie",
    desc: "Walkie Agent managed through the Karnel ai_tools module.",
  },
  {
    name: "Hugging Face",
    flag: "--hugging-face",
    desc: "Hugging Face managed through the Karnel ai_tools module.",
  },
] as const;

export const DEV_TOOLS = [
  { name: "Gh", flag: "--gh", desc: "Manage GitHub from the terminal" },
  { name: "Wget", flag: "--wget", desc: "Network downloader" },
  { name: "Curl", flag: "--curl", desc: "HTTP client" },
  { name: "Lsd", flag: "--lsd", desc: "Modern ls with icons" },
  { name: "Bat", flag: "--bat", desc: "Modern cat with syntax highlighting" },
  {
    name: "Proot",
    flag: "--proot",
    desc: "Isolated Linux environment without root",
  },
  { name: "Ncurses", flag: "--ncurses", desc: "Terminal utilities" },
  { name: "Tmate", flag: "--tmate", desc: "Terminal sharing" },
  {
    name: "Openssh",
    flag: "--openssh",
    desc: "Secure shell client and server",
  },
  { name: "Tmux", flag: "--tmux", desc: "Terminal multiplexer" },
  { name: "Cloudflared", flag: "--cloudflared", desc: "Cloudflare tunnel" },
  { name: "Translate", flag: "--translate", desc: "Terminal translator" },
  { name: "Html2text", flag: "--html2text", desc: "Convert HTML to text" },
  { name: "Jq", flag: "--jq", desc: "JSON processor" },
  { name: "Bc", flag: "--bc", desc: "Precision calculator" },
  { name: "Tree", flag: "--tree", desc: "Display directory trees" },
  { name: "Fzf", flag: "--fzf", desc: "Fuzzy finder" },
  { name: "Imagemagick", flag: "--imagemagick", desc: "Image manipulation" },
  { name: "Shfmt", flag: "--shfmt", desc: "Shell formatter" },
  { name: "Make", flag: "--make", desc: "Build automation" },
  { name: "Udocker", flag: "--udocker", desc: "Rootless containers" },
  { name: "Snyk", flag: "--snyk", desc: "Security scanner" },
] as const;

export const NETWORK_TOOLS = [
  {
    name: "Dark",
    flag: "--dark",
    desc: "Tor crawler and scraper for OSINT research",
  },
  {
    name: "Dedsec Network",
    flag: "--dedsec-network",
    desc: "Multi-purpose network scanner, OSINT, and pentest",
  },
] as const;

export const UTILS_TOOLS = [
  {
    name: "Fconv",
    flag: "--fconv",
    desc: "Convert files between common formats",
  },
  {
    name: "Filecheck",
    flag: "--filecheck",
    desc: "Inspect file integrity and metadata",
  },
  { name: "Websites", flag: "--websites", desc: "Scaffold website projects" },
  { name: "Notes", flag: "--notes", desc: "Manage notes from the terminal" },
  {
    name: "Treex",
    flag: "--treex",
    desc: "Explore project trees interactively",
  },
  { name: "Passman", flag: "--passman", desc: "Local password management" },
  {
    name: "Applaunch",
    flag: "--applaunch",
    desc: "Launch installed applications",
  },
  { name: "Splash", flag: "--splash", desc: "Customize the startup splash" },
  { name: "Httptmux", flag: "--httptmux", desc: "Interactive API client" },
  { name: "Zork", flag: "--zork", desc: "Classic text adventures" },
  {
    name: "Qrcode",
    flag: "--qrcode",
    desc: "Generate QR codes from URLs and text",
  },
  { name: "Superfile", flag: "--superfile", desc: "Terminal file manager" },
  {
    name: "Herdr",
    flag: "--herdr",
    desc: "Herdr managed through the Karnel utils_tools module.",
  },
] as const;

export const OSINT_TOOLS = [
  {
    name: "Robin",
    flag: "--robin",
    desc: "AI-assisted dark-web OSINT through Tor and a loopback-only Streamlit UI",
  },
] as const;

export const LANG_TOOLS = [
  { name: "Bun", flag: "--bun", desc: "Fast all-in-one JavaScript runtime" },
  { name: "Nodejs", flag: "--nodejs", desc: "V8-based JavaScript runtime" },
  {
    name: "Python",
    flag: "--python",
    desc: "Versatile language for scripts and apps",
  },
  { name: "Perl", flag: "--perl", desc: "Text processing and scripting" },
  { name: "Php", flag: "--php", desc: "Web server language" },
  {
    name: "Rust",
    flag: "--rust",
    desc: "Systems programming with safety and performance",
  },
  { name: "Clang", flag: "--clang", desc: "Native compilation with Clang/GCC" },
  { name: "Golang", flag: "--golang", desc: "Compiled concurrent language" },
] as const;

export const DB_TOOLS = [
  {
    name: "Postgresql",
    flag: "--postgresql",
    desc: "Advanced relational database",
  },
  { name: "Mariadb", flag: "--mariadb", desc: "MySQL-compatible, robust" },
  { name: "Sqlite", flag: "--sqlite", desc: "Embedded lightweight database" },
  { name: "Mongodb", flag: "--mongodb", desc: "NoSQL document database" },
  {
    name: "Redis",
    flag: "--redis",
    desc: "In-memory cache and message broker",
  },
] as const;

export const EDITOR_TOOLS = [
  { name: "Code Server", flag: "--code-server", desc: "VS Code in browser" },
  { name: "Neovim", flag: "--neovim", desc: "Modern Vim-based editor" },
  { name: "Nvchad", flag: "--nvchad", desc: "Neovim IDE configuration" },
] as const;

export const AUTO_TOOLS = [
  {
    name: "N8n",
    flag: "--n8n",
    desc: "Workflow automation platform with visual flows",
  },
] as const;

export const DEPLOY_TOOLS = [
  { name: "Railway", flag: "--railway", desc: "Full-stack with databases" },
  { name: "Netlify", flag: "--netlify", desc: "Static sites & edge functions" },
  { name: "Vercel", flag: "--vercel", desc: "Frontend deployment platform" },
  {
    name: "Supabase",
    flag: "--supabase",
    desc: "Supabase managed through the Karnel deploy_tools module.",
  },
] as const;

export const NPM_TOOLS = [
  { name: "Typescript", flag: "--typescript", desc: "JavaScript with types" },
  { name: "Nestjs", flag: "--nestjs", desc: "Progressive Node.js framework" },
  { name: "Prettier", flag: "--prettier", desc: "Code formatter" },
  {
    name: "Live Server",
    flag: "--live-server",
    desc: "Server with live reload",
  },
  {
    name: "Localtunnel",
    flag: "--localtunnel",
    desc: "Public tunnels for localhost",
  },
  { name: "Vercel", flag: "--vercel", desc: "Deploy to Vercel" },
  { name: "Markserv", flag: "--markserv", desc: "Markdown server" },
  { name: "Psqlformat", flag: "--psqlformat", desc: "SQL formatter" },
  { name: "Ncu", flag: "--ncu", desc: "Check package updates" },
  {
    name: "Turbopack",
    flag: "--turbopack",
    desc: "Extremely fast Rust bundler",
  },
  { name: "Ngrok", flag: "--ngrok", desc: "Public tunnels for localhost" },
] as const;

export const SHELL_TOOLS = [
  {
    name: "Powerlevel10k",
    flag: "--powerlevel10k",
    desc: "Fastest and most beautiful ZSH theme",
  },
  { name: "Zsh Defer", flag: "--zsh-defer", desc: "Async plugin loading" },
  {
    name: "Zsh Autosuggestions",
    flag: "--zsh-autosuggestions",
    desc: "Fish-style autocomplete",
  },
  {
    name: "Zsh Syntax Highlighting",
    flag: "--zsh-syntax-highlighting",
    desc: "Syntax highlighting in commands",
  },
  {
    name: "History Substring",
    flag: "--history-substring",
    desc: "Fish-style history search",
  },
  {
    name: "Zsh Completions",
    flag: "--zsh-completions",
    desc: "Extra completion definitions",
  },
  { name: "Fzf Tab", flag: "--fzf-tab", desc: "Fuzzy tab completion with fzf" },
  {
    name: "You Should Use",
    flag: "--you-should-use",
    desc: "Reminds you of existing aliases",
  },
  {
    name: "Zsh Autopair",
    flag: "--zsh-autopair",
    desc: "Auto-close brackets and quotes",
  },
  { name: "Better Npm", flag: "--better-npm", desc: "Improved npm completion" },
] as const;

export const UI_TOOLS = [
  { name: "Font", flag: "--font", desc: "Font with ligatures and icons" },
  {
    name: "Extra Keys",
    flag: "--extra-keys",
    desc: "Additional keys on Termux keyboard",
  },
  { name: "Cursor", flag: "--cursor", desc: "Styled cursor with gradient" },
  {
    name: "Banner",
    flag: "--banner",
    desc: "ASCII banner with metallic effect on startup",
  },
] as const;

export const GAMES_TOOLS = [
  { name: "Buzz", flag: "--buzz", desc: "Quiz game with multiple categories" },
  {
    name: "Ctfgod",
    flag: "--ctfgod",
    desc: "Capture The Flag challenge solver",
  },
  {
    name: "Detective",
    flag: "--detective",
    desc: "Mystery investigation game",
  },
  { name: "Pet Friends", flag: "--pet-friends", desc: "Virtual pet simulator" },
  { name: "Tamagotchi", flag: "--tamagotchi", desc: "Retro digital pet" },
  {
    name: "Arcade",
    flag: "--arcade",
    desc: "Classic arcade games in terminal",
  },
] as const;

export const SECURITY_TOOLS = [
  {
    name: "Nmap",
    flag: "--nmap",
    desc: "Nmap managed through the Karnel security_tools module.",
  },
  {
    name: "Hydra",
    flag: "--hydra",
    desc: "Hydra managed through the Karnel security_tools module.",
  },
  {
    name: "Nikto",
    flag: "--nikto",
    desc: "Nikto managed through the Karnel security_tools module.",
  },
  {
    name: "Sqlmap",
    flag: "--sqlmap",
    desc: "Sqlmap managed through the Karnel security_tools module.",
  },
  {
    name: "Gobuster",
    flag: "--gobuster",
    desc: "Gobuster managed through the Karnel security_tools module.",
  },
  {
    name: "Dirb",
    flag: "--dirb",
    desc: "Dirb managed through the Karnel security_tools module.",
  },
  {
    name: "Wpscan",
    flag: "--wpscan",
    desc: "Wpscan managed through the Karnel security_tools module.",
  },
  {
    name: "John",
    flag: "--john",
    desc: "John managed through the Karnel security_tools module.",
  },
  {
    name: "Aircrack Ng",
    flag: "--aircrack-ng",
    desc: "Aircrack Ng managed through the Karnel security_tools module.",
  },
  {
    name: "Metasploit",
    flag: "--metasploit",
    desc: "Metasploit managed through the Karnel security_tools module.",
  },
  {
    name: "Burpsuite",
    flag: "--burpsuite",
    desc: "Burpsuite managed through the Karnel security_tools module.",
  },
  {
    name: "Zap",
    flag: "--zap",
    desc: "Zap managed through the Karnel security_tools module.",
  },
  {
    name: "Enum4linux",
    flag: "--enum4linux",
    desc: "Enum4linux managed through the Karnel security_tools module.",
  },
  {
    name: "Smbclient",
    flag: "--smbclient",
    desc: "Smbclient managed through the Karnel security_tools module.",
  },
  {
    name: "Ffuf",
    flag: "--ffuf",
    desc: "Ffuf managed through the Karnel security_tools module.",
  },
  {
    name: "Whatweb",
    flag: "--whatweb",
    desc: "Whatweb managed through the Karnel security_tools module.",
  },
  {
    name: "Wafw00f",
    flag: "--wafw00f",
    desc: "Wafw00f managed through the Karnel security_tools module.",
  },
  {
    name: "Dnsrecon",
    flag: "--dnsrecon",
    desc: "Dnsrecon managed through the Karnel security_tools module.",
  },
  {
    name: "Theharvester",
    flag: "--theharvester",
    desc: "Theharvester managed through the Karnel security_tools module.",
  },
  {
    name: "Subfinder",
    flag: "--subfinder",
    desc: "Subfinder managed through the Karnel security_tools module.",
  },
  {
    name: "Amass",
    flag: "--amass",
    desc: "Amass managed through the Karnel security_tools module.",
  },
  {
    name: "Masscan",
    flag: "--masscan",
    desc: "Masscan managed through the Karnel security_tools module.",
  },
  {
    name: "Netcat",
    flag: "--netcat",
    desc: "Netcat managed through the Karnel security_tools module.",
  },
  {
    name: "Tcpdump",
    flag: "--tcpdump",
    desc: "Tcpdump managed through the Karnel security_tools module.",
  },
  {
    name: "Whois",
    flag: "--whois",
    desc: "Whois managed through the Karnel security_tools module.",
  },
  {
    name: "Hashcat",
    flag: "--hashcat",
    desc: "Hashcat managed through the Karnel security_tools module.",
  },
  {
    name: "Binwalk",
    flag: "--binwalk",
    desc: "Binwalk managed through the Karnel security_tools module.",
  },
  {
    name: "Foremost",
    flag: "--foremost",
    desc: "Foremost managed through the Karnel security_tools module.",
  },
  {
    name: "Steghide",
    flag: "--steghide",
    desc: "Steghide managed through the Karnel security_tools module.",
  },
  {
    name: "Exiftool",
    flag: "--exiftool",
    desc: "Exiftool managed through the Karnel security_tools module.",
  },
] as const;

export const CATALOG_COUNTS = {
  ai: AI_TOOLS.length,
  dev: DEV_TOOLS.length,
  network: NETWORK_TOOLS.length,
  utils: UTILS_TOOLS.length,
  osint: OSINT_TOOLS.length,
  lang: LANG_TOOLS.length,
  db: DB_TOOLS.length,
  editor: EDITOR_TOOLS.length,
  auto: AUTO_TOOLS.length,
  deploy: DEPLOY_TOOLS.length,
  npm: NPM_TOOLS.length,
  shell: SHELL_TOOLS.length,
  ui: UI_TOOLS.length,
  games: GAMES_TOOLS.length,
  security: SECURITY_TOOLS.length,
} as const;
