// Auto-generated by scripts/generate-catalog.mjs
// DO NOT EDIT — source of truth is karnel-termux CLI registries.
// Run: node scripts/generate-catalog.mjs

export const AI_TOOLS = [
  {
    name: "10Router",
    flag: "--10router",
    desc: "Multi-agent orchestrator for parallel AI tasks",
  },
  {
    name: "Qwen Code",
    flag: "--qwen-code",
    desc: "Alibaba coding assistant with multilingual support",
  },
  {
    name: "Gemini CLI",
    flag: "--gemini-cli",
    desc: "Google Gemini AI assistant",
  },
  {
    name: "Claude Code",
    flag: "--claude-code",
    desc: "Anthropic Claude coding agent",
  },
  {
    name: "Mistral Vibe",
    flag: "--mistral-vibe",
    desc: "Mistral AI coding assistant",
  },
  {
    name: "OpenClaude",
    flag: "--openclaude",
    desc: "Self-hosted Claude-compatible agent",
  },
  {
    name: "OpenClaw",
    flag: "--openclaw",
    desc: "Lightweight Claude-compatible CLI",
  },
  { name: "Ollama", flag: "--ollama", desc: "Run open-source LLMs locally" },
  { name: "Codex CLI", flag: "--codex", desc: "OpenAI Codex coding agent" },
  {
    name: "OpenCode",
    flag: "--opencode",
    desc: "Terminal-native AI coding assistant",
  },
  { name: "MiMo Code", flag: "--mimocode", desc: "Xiaomi MiMo coding agent" },
  {
    name: "Engram",
    flag: "--engram",
    desc: "Persistent memory for AI sessions",
  },
  {
    name: "CodeGraph",
    flag: "--codegraph",
    desc: "AI code analysis and graph visualization",
  },
  { name: "Pi Coding Agent", flag: "--pi", desc: "Minimalist AI coding agent" },
  {
    name: "Antigravity CLI",
    flag: "--antigravity-cli",
    desc: "Agentic coding assistant",
  },
  {
    name: "Minimax CLI",
    flag: "--minimax-cli",
    desc: "Minimax AI coding agent",
  },
  {
    name: "Gentle AI",
    flag: "--gentle-ai",
    desc: "AI pair programmer with guardrails",
  },
  { name: "GGA", flag: "--gga", desc: "Google Gemini agent for coding" },
  {
    name: "Hermes Agent",
    flag: "--hermes-agent",
    desc: "NousResearch Hermes agent",
  },
  {
    name: "Kimi Code",
    flag: "--kimi-code",
    desc: "Moonshot Kimi coding assistant",
  },
  {
    name: "Command Code",
    flag: "--command-code",
    desc: "Command-line AI coding agent",
  },
  { name: "Codebuff", flag: "--codebuff", desc: "AI pair programmer" },
  { name: "Freebuff", flag: "--freebuff", desc: "Free AI coding assistant" },
  {
    name: "Kilo Code CLI",
    flag: "--kilocode-cli",
    desc: "Hosted coding-agent CLI",
  },
  { name: "Kiro CLI", flag: "--kiro", desc: "AI-powered IDE agent" },
  { name: "Crush CLI", flag: "--crush", desc: "Anthropic Crush coding agent" },
  { name: "Cline CLI", flag: "--cline", desc: "VS Code AI extension CLI" },
  { name: "Odysseus", flag: "--odysseus", desc: "Autonomous AI coding agent" },
  {
    name: "Kimchi CLI",
    flag: "--kimchi-code",
    desc: "Korean-focused AI coding assistant",
  },
  {
    name: "omniRoute",
    flag: "--omni-route",
    desc: "Multi-model AI routing proxy",
  },
  {
    name: "Context7 Documentation Provider",
    flag: "--ctx7",
    desc: "Documentation context provider for AI agents",
  },
  {
    name: "OpenSpec SDD Framework",
    flag: "--openspec",
    desc: "AI-powered specification-driven development",
  },
  {
    name: "Supercode CLI",
    flag: "--supercode-cli",
    desc: "AI coding assistant with multi-model support",
  },
  {
    name: "Puter CLI",
    flag: "--puter",
    desc: "Cloud desktop and AI agent platform",
  },
  { name: "KeelCode", flag: "--keelcode", desc: "Hosted coding-agent CLI" },
  {
    name: "Copilot-Termux",
    flag: "--copilot-termux",
    desc: "GitHub Copilot for Termux",
  },
  {
    name: "Qoder",
    flag: "--qoder",
    desc: "AI coding agent with codebase understanding",
  },
  {
    name: "AMP Code CLI",
    flag: "--ampcode",
    desc: "Sourcegraph Amp AI coding agent",
  },
  {
    name: "Cursor CLI",
    flag: "--cursor-cli",
    desc: "Cursor AI editor CLI agent",
  },
  {
    name: "Oh-My-Pi",
    flag: "--oh-my-pi",
    desc: "AI agent framework for Raspberry Pi",
  },
  {
    name: "Goose CLI",
    flag: "--goose",
    desc: "AI agent that executes code and commands",
  },
  {
    name: "Factory Droid",
    flag: "--droid",
    desc: "Factory Droid autonomous coding agent",
  },
  {
    name: "Cactus",
    flag: "--cactus",
    desc: "AI coding agent with codebase awareness",
  },
  {
    name: "Cactus Needle",
    flag: "--cactus-needle",
    desc: "Cactus agent remote execution layer",
  },
  {
    name: "Walkie Agent",
    flag: "--walkie",
    desc: "Voice-controlled AI coding agent",
  },
  {
    name: "Hugging Face",
    flag: "--hugging-face",
    desc: "Hugging Face model hub CLI",
  },
] as const;

export const DEV_TOOLS = [
  { name: "Gh", flag: "--gh", desc: "Manage GitHub from the terminal" },
  { name: "Wget", flag: "--wget", desc: "Network downloader" },
  { name: "Curl", flag: "--curl", desc: "HTTP client" },
  { name: "Lsd", flag: "--lsd", desc: "Modern ls with icons" },
  { name: "Bat", flag: "--bat", desc: "Modern cat with syntax highlighting" },
  {
    name: "Proot",
    flag: "--proot",
    desc: "Isolated Linux environment without root",
  },
  { name: "Ncurses", flag: "--ncurses", desc: "Terminal utilities" },
  { name: "Tmate", flag: "--tmate", desc: "Terminal sharing" },
  {
    name: "Openssh",
    flag: "--openssh",
    desc: "Secure shell client and server",
  },
  { name: "Tmux", flag: "--tmux", desc: "Terminal multiplexer" },
  { name: "Cloudflared", flag: "--cloudflared", desc: "Cloudflare tunnel" },
  { name: "Translate", flag: "--translate", desc: "Terminal translator" },
  { name: "Html2text", flag: "--html2text", desc: "Convert HTML to text" },
  { name: "Jq", flag: "--jq", desc: "JSON processor" },
  { name: "Bc", flag: "--bc", desc: "Precision calculator" },
  { name: "Tree", flag: "--tree", desc: "Display directory trees" },
  { name: "Fzf", flag: "--fzf", desc: "Fuzzy finder" },
  { name: "Imagemagick", flag: "--imagemagick", desc: "Image manipulation" },
  { name: "Shfmt", flag: "--shfmt", desc: "Shell formatter" },
  { name: "Make", flag: "--make", desc: "Build automation" },
  { name: "Udocker", flag: "--udocker", desc: "Rootless containers" },
  { name: "Snyk", flag: "--snyk", desc: "Security scanner" },
] as const;

export const NETWORK_TOOLS = [
  {
    name: "Dark",
    flag: "--dark",
    desc: "Tor crawler and scraper for OSINT research",
  },
  {
    name: "Dedsec Network",
    flag: "--dedsec-network",
    desc: "Multi-purpose network scanner, OSINT, and pentest",
  },
] as const;

export const UTILS_TOOLS = [
  {
    name: "Fconv",
    flag: "--fconv",
    desc: "Convert files between common formats",
  },
  {
    name: "Filecheck",
    flag: "--filecheck",
    desc: "Inspect file integrity and metadata",
  },
  { name: "Websites", flag: "--websites", desc: "Scaffold website projects" },
  { name: "Notes", flag: "--notes", desc: "Manage notes from the terminal" },
  {
    name: "Treex",
    flag: "--treex",
    desc: "Explore project trees interactively",
  },
  { name: "Passman", flag: "--passman", desc: "Local password management" },
  {
    name: "Applaunch",
    flag: "--applaunch",
    desc: "Launch installed applications",
  },
  { name: "Splash", flag: "--splash", desc: "Customize the startup splash" },
  { name: "Httptmux", flag: "--httptmux", desc: "Interactive API client" },
  { name: "Zork", flag: "--zork", desc: "Classic text adventures" },
  {
    name: "Qrcode",
    flag: "--qrcode",
    desc: "Generate QR codes from URLs and text",
  },
  { name: "Superfile", flag: "--superfile", desc: "Terminal file manager" },
  {
    name: "Herdr",
    flag: "--herdr",
    desc: "Herdr managed through the Karnel utils_tools module.",
  },
] as const;

export const OSINT_TOOLS = [
  {
    name: "Robin",
    flag: "--robin",
    desc: "AI-assisted dark-web OSINT through Tor and a loopback-only Streamlit UI",
  },
] as const;

export const LANG_TOOLS = [
  { name: "Bun", flag: "--bun", desc: "Fast all-in-one JavaScript runtime" },
  { name: "Nodejs", flag: "--nodejs", desc: "V8-based JavaScript runtime" },
  {
    name: "Python",
    flag: "--python",
    desc: "Versatile language for scripts and apps",
  },
  { name: "Perl", flag: "--perl", desc: "Text processing and scripting" },
  { name: "Php", flag: "--php", desc: "Web server language" },
  {
    name: "Rust",
    flag: "--rust",
    desc: "Systems programming with safety and performance",
  },
  { name: "Clang", flag: "--clang", desc: "Native compilation with Clang/GCC" },
  { name: "Golang", flag: "--golang", desc: "Compiled concurrent language" },
] as const;

export const DB_TOOLS = [
  {
    name: "Postgresql",
    flag: "--postgresql",
    desc: "Advanced relational database",
  },
  { name: "Mariadb", flag: "--mariadb", desc: "MySQL-compatible, robust" },
  { name: "Sqlite", flag: "--sqlite", desc: "Embedded lightweight database" },
  { name: "Mongodb", flag: "--mongodb", desc: "NoSQL document database" },
  {
    name: "Redis",
    flag: "--redis",
    desc: "In-memory cache and message broker",
  },
] as const;

export const EDITOR_TOOLS = [
  { name: "Code Server", flag: "--code-server", desc: "VS Code in browser" },
  { name: "Neovim", flag: "--neovim", desc: "Modern Vim-based editor" },
  { name: "Nvchad", flag: "--nvchad", desc: "Neovim IDE configuration" },
] as const;

export const AUTO_TOOLS = [
  {
    name: "N8n",
    flag: "--n8n",
    desc: "Workflow automation platform with visual flows",
  },
] as const;

export const DEPLOY_TOOLS = [
  { name: "Railway", flag: "--railway", desc: "Full-stack with databases" },
  { name: "Netlify", flag: "--netlify", desc: "Static sites & edge functions" },
  { name: "Vercel", flag: "--vercel", desc: "Frontend deployment platform" },
  {
    name: "Supabase CLI",
    flag: "--supabase",
    desc: "Supabase CLI for project workflows; its native binary is not supported on Android/Termux.",
  },
] as const;

export const NPM_TOOLS = [
  { name: "Typescript", flag: "--typescript", desc: "JavaScript with types" },
  { name: "Nestjs", flag: "--nestjs", desc: "Progressive Node.js framework" },
  { name: "Prettier", flag: "--prettier", desc: "Code formatter" },
  {
    name: "Live Server",
    flag: "--live-server",
    desc: "Server with live reload",
  },
  {
    name: "Localtunnel",
    flag: "--localtunnel",
    desc: "Public tunnels for localhost",
  },
  { name: "Vercel", flag: "--vercel", desc: "Deploy to Vercel" },
  { name: "Markserv", flag: "--markserv", desc: "Markdown server" },
  { name: "Psqlformat", flag: "--psqlformat", desc: "SQL formatter" },
  { name: "Ncu", flag: "--ncu", desc: "Check package updates" },
  {
    name: "Turbopack",
    flag: "--turbopack",
    desc: "Extremely fast Rust bundler",
  },
  { name: "Ngrok", flag: "--ngrok", desc: "Public tunnels for localhost" },
] as const;

export const SHELL_TOOLS = [
  {
    name: "Powerlevel10k",
    flag: "--powerlevel10k",
    desc: "Fastest and most beautiful ZSH theme",
  },
  { name: "Zsh Defer", flag: "--zsh-defer", desc: "Async plugin loading" },
  {
    name: "Zsh Autosuggestions",
    flag: "--zsh-autosuggestions",
    desc: "Fish-style autocomplete",
  },
  {
    name: "Zsh Syntax Highlighting",
    flag: "--zsh-syntax-highlighting",
    desc: "Syntax highlighting in commands",
  },
  {
    name: "History Substring",
    flag: "--history-substring",
    desc: "Fish-style history search",
  },
  {
    name: "Zsh Completions",
    flag: "--zsh-completions",
    desc: "Extra completion definitions",
  },
  { name: "Fzf Tab", flag: "--fzf-tab", desc: "Fuzzy tab completion with fzf" },
  {
    name: "You Should Use",
    flag: "--you-should-use",
    desc: "Reminds you of existing aliases",
  },
  {
    name: "Zsh Autopair",
    flag: "--zsh-autopair",
    desc: "Auto-close brackets and quotes",
  },
  { name: "Better Npm", flag: "--better-npm", desc: "Improved npm completion" },
] as const;

export const UI_TOOLS = [
  { name: "Font", flag: "--font", desc: "Font with ligatures and icons" },
  {
    name: "Extra Keys",
    flag: "--extra-keys",
    desc: "Additional keys on Termux keyboard",
  },
  { name: "Cursor", flag: "--cursor", desc: "Styled cursor with gradient" },
  {
    name: "Banner",
    flag: "--banner",
    desc: "ASCII banner with metallic effect on startup",
  },
] as const;

export const GAMES_TOOLS = [
  { name: "Buzz", flag: "--buzz", desc: "Quiz game with multiple categories" },
  {
    name: "Ctfgod",
    flag: "--ctfgod",
    desc: "Capture The Flag challenge solver",
  },
  {
    name: "Detective",
    flag: "--detective",
    desc: "Mystery investigation game",
  },
  { name: "Pet Friends", flag: "--pet-friends", desc: "Virtual pet simulator" },
  { name: "Tamagotchi", flag: "--tamagotchi", desc: "Retro digital pet" },
  {
    name: "Arcade",
    flag: "--arcade",
    desc: "Classic arcade games in terminal",
  },
] as const;

export const SECURITY_TOOLS = [
  { name: "Nmap", flag: "--nmap", desc: "Network discovery and port scanner" },
  { name: "Hydra", flag: "--hydra", desc: "Brute-force login cracker" },
  { name: "Nikto", flag: "--nikto", desc: "Web server vulnerability scanner" },
  { name: "Sqlmap", flag: "--sqlmap", desc: "SQL injection automation tool" },
  {
    name: "Gobuster",
    flag: "--gobuster",
    desc: "Directory and DNS brute-force scanner",
  },
  { name: "Dirb", flag: "--dirb", desc: "Web content scanner" },
  { name: "Wpscan", flag: "--wpscan", desc: "WordPress security scanner" },
  { name: "John", flag: "--john", desc: "Password hash cracker" },
  {
    name: "Aircrack Ng",
    flag: "--aircrack-ng",
    desc: "WiFi network auditing toolkit",
  },
  {
    name: "Metasploit",
    flag: "--metasploit",
    desc: "Penetration testing framework",
  },
  {
    name: "Burpsuite",
    flag: "--burpsuite",
    desc: "Web application security testing",
  },
  {
    name: "Zap",
    flag: "--zap",
    desc: "OWASP web application security scanner",
  },
  {
    name: "Enum4linux",
    flag: "--enum4linux",
    desc: "SMB/NetBIOS enumeration tool",
  },
  { name: "Smbclient", flag: "--smbclient", desc: "SMB file sharing client" },
  { name: "Ffuf", flag: "--ffuf", desc: "Fast web fuzzer" },
  { name: "Whatweb", flag: "--whatweb", desc: "Web technology fingerprinter" },
  { name: "Wafw00f", flag: "--wafw00f", desc: "WAF detection tool" },
  {
    name: "Dnsrecon",
    flag: "--dnsrecon",
    desc: "DNS enumeration and reconnaissance",
  },
  {
    name: "Theharvester",
    flag: "--theharvester",
    desc: "Email and subdomain harvester",
  },
  { name: "Subfinder", flag: "--subfinder", desc: "Subdomain discovery tool" },
  { name: "Amass", flag: "--amass", desc: "Attack surface mapping tool" },
  { name: "Masscan", flag: "--masscan", desc: "Fast port scanner" },
  { name: "Netcat", flag: "--netcat", desc: "Network Swiss army knife" },
  { name: "Tcpdump", flag: "--tcpdump", desc: "Network packet analyzer" },
  { name: "Whois", flag: "--whois", desc: "Domain ownership lookup" },
  { name: "Hashcat", flag: "--hashcat", desc: "Advanced password recovery" },
  { name: "Binwalk", flag: "--binwalk", desc: "Firmware analysis tool" },
  { name: "Foremost", flag: "--foremost", desc: "File recovery tool" },
  { name: "Steghide", flag: "--steghide", desc: "Steganography tool" },
  { name: "Exiftool", flag: "--exiftool", desc: "Metadata reader and editor" },
] as const;

export const CATALOG_COUNTS = {
  ai: AI_TOOLS.length,
  dev: DEV_TOOLS.length,
  network: NETWORK_TOOLS.length,
  utils: UTILS_TOOLS.length,
  osint: OSINT_TOOLS.length,
  lang: LANG_TOOLS.length,
  db: DB_TOOLS.length,
  editor: EDITOR_TOOLS.length,
  auto: AUTO_TOOLS.length,
  deploy: DEPLOY_TOOLS.length,
  npm: NPM_TOOLS.length,
  shell: SHELL_TOOLS.length,
  ui: UI_TOOLS.length,
  games: GAMES_TOOLS.length,
  security: SECURITY_TOOLS.length,
} as const;
