// Auto-generated by scripts/generate-catalog.mjs
// DO NOT EDIT — source of truth is karnel-termux CLI registries.
// Run: node scripts/generate-catalog.mjs

export const AI_TOOLS = [
  { name: "Qwen Code", flag: "--qwen", desc: "" },
  { name: "Gemini CLI", flag: "--gemini", desc: "" },
  { name: "Claude Code", flag: "--claude", desc: "" },
  { name: "Mistral Vibe", flag: "--vibe", desc: "" },
  { name: "OpenClaude", flag: "--openclaude", desc: "" },
  { name: "OpenClaw", flag: "--openclaw", desc: "" },
  { name: "Ollama", flag: "--ollama", desc: "" },
  { name: "Codex CLI", flag: "--codex", desc: "" },
  { name: "OpenCode", flag: "--opencode", desc: "" },
  { name: "MiMo Code", flag: "--mimo", desc: "" },
  { name: "Engram", flag: "--engram", desc: "" },
  { name: "CodeGraph", flag: "--codegraph", desc: "" },
  { name: "Pi Coding Agent", flag: "--pi", desc: "" },
  { name: "Antigravity CLI", flag: "--agy", desc: "" },
  { name: "Minimax CLI", flag: "--mmx", desc: "" },
  { name: "Gentle AI", flag: "--gentle-ai", desc: "" },
  { name: "GGA", flag: "--gga", desc: "" },
  { name: "Hermes Agent", flag: "--hermes", desc: "" },
  { name: "Kimi Code", flag: "--kimi", desc: "" },
  { name: "Command Code", flag: "--command-code", desc: "" },
  { name: "Freebuff", flag: "--freebuff", desc: "" },
  { name: "Kilo Code CLI", flag: "--kilocode,kilo", desc: "" },
  { name: "Kiro CLI", flag: "--kiro,kiro-cli", desc: "" },
  { name: "Crush CLI", flag: "--crush", desc: "" },
  { name: "Cline CLI", flag: "--cline", desc: "" },
  { name: "Odysseus", flag: "--odysseus", desc: "" },
  { name: "Kimchi CLI", flag: "--kimchi", desc: "" },
  { name: "omniRoute", flag: "--omni-route", desc: "" },
  { name: "Context7 Documentation Provider", flag: "--ctx7", desc: "" },
  { name: "OpenSpec SDD Framework", flag: "--openspec", desc: "" },
  { name: "Copilot-Termux", flag: "--copilot", desc: "" },
  { name: "Qoder", flag: "--qodercli", desc: "" },
] as const;

export const DEV_TOOLS = [
  { name: "Gh", flag: "--gh", desc: "Manage GitHub from the terminal" },
  { name: "Wget", flag: "--wget", desc: "Network downloader" },
  { name: "Curl", flag: "--curl", desc: "HTTP client" },
  { name: "Lsd", flag: "--lsd", desc: "Modern ls with icons" },
  { name: "Bat", flag: "--bat", desc: "Modern cat with syntax highlighting" },
  { name: "Proot", flag: "--proot", desc: "Isolated Linux environment without root" },
  { name: "Ncurses", flag: "--ncurses", desc: "Terminal utilities" },
  { name: "Tmate", flag: "--tmate", desc: "Terminal sharing" },
  { name: "Openssh", flag: "--openssh", desc: "Secure shell client and server" },
  { name: "Tmux", flag: "--tmux", desc: "Terminal multiplexer" },
  { name: "Cloudflared", flag: "--cloudflared", desc: "Cloudflare tunnel" },
  { name: "Translate", flag: "--translate", desc: "Terminal translator" },
  { name: "Html2text", flag: "--html2text", desc: "Convert HTML to text" },
  { name: "Jq", flag: "--jq", desc: "JSON processor" },
  { name: "Bc", flag: "--bc", desc: "Precision calculator" },
  { name: "Tree", flag: "--tree", desc: "Display directory trees" },
  { name: "Fzf", flag: "--fzf", desc: "Fuzzy finder" },
  { name: "Imagemagick", flag: "--imagemagick", desc: "Image manipulation" },
  { name: "Shfmt", flag: "--shfmt", desc: "Shell formatter" },
  { name: "Make", flag: "--make", desc: "Build automation" },
  { name: "Udocker", flag: "--udocker", desc: "Rootless containers" },
  { name: "Snyk", flag: "--snyk", desc: "Security scanner" },
] as const;

export const NETWORK_TOOLS = [
  { name: "Dark", flag: "--dark", desc: "Tor crawler and scraper for OSINT research" },
  { name: "Dedsec Network", flag: "--dedsec-network", desc: "Multi-purpose network scanner, OSINT, and pentest" },
] as const;

export const UTILS_TOOLS = [
  { name: "Fconv", flag: "--fconv", desc: "Convert files between common formats" },
  { name: "Filecheck", flag: "--filecheck", desc: "Inspect file integrity and metadata" },
  { name: "Websites", flag: "--websites", desc: "Scaffold website projects" },
  { name: "Notes", flag: "--notes", desc: "Manage notes from the terminal" },
  { name: "Treex", flag: "--treex", desc: "Explore project trees interactively" },
  { name: "Passman", flag: "--passman", desc: "Local password management" },
  { name: "Applaunch", flag: "--applaunch", desc: "Launch installed applications" },
  { name: "Splash", flag: "--splash", desc: "Customize the startup splash" },
  { name: "Httptmux", flag: "--httptmux", desc: "Interactive API client" },
  { name: "Zork", flag: "--zork", desc: "Classic text adventures" },
  { name: "Qrcode", flag: "--qrcode", desc: "Generate QR codes from URLs and text" },
] as const;

export const OSINT_TOOLS = [
  { name: "Robin", flag: "--robin", desc: "AI-assisted dark-web OSINT through Tor and a loopback-only Streamlit UI" },
] as const;

export const LANG_TOOLS = [
  { name: "Bun", flag: "--bun", desc: "Fast all-in-one JavaScript runtime" },
  { name: "Nodejs", flag: "--nodejs", desc: "V8-based JavaScript runtime" },
  { name: "Python", flag: "--python", desc: "Versatile language for scripts and apps" },
  { name: "Perl", flag: "--perl", desc: "Text processing and scripting" },
  { name: "Php", flag: "--php", desc: "Web server language" },
  { name: "Rust", flag: "--rust", desc: "Systems programming with safety and performance" },
  { name: "Clang", flag: "--clang", desc: "Native compilation with Clang/GCC" },
  { name: "Golang", flag: "--golang", desc: "Compiled concurrent language" },
] as const;

export const DB_TOOLS = [
  { name: "Postgresql", flag: "--postgresql", desc: "Advanced relational database" },
  { name: "Mariadb", flag: "--mariadb", desc: "MySQL-compatible, robust" },
  { name: "Sqlite", flag: "--sqlite", desc: "Embedded lightweight database" },
  { name: "Mongodb", flag: "--mongodb", desc: "NoSQL document database" },
  { name: "Redis", flag: "--redis", desc: "In-memory cache and message broker" },
] as const;

export const EDITOR_TOOLS = [
  { name: "Code Server", flag: "--code-server", desc: "VS Code in browser" },
  { name: "Neovim", flag: "--neovim", desc: "Modern Vim-based editor" },
  { name: "Nvchad", flag: "--nvchad", desc: "Neovim IDE configuration" },
] as const;

export const AUTO_TOOLS = [
  { name: "N8n", flag: "--n8n", desc: "Workflow automation platform with visual flows" },
] as const;

export const DEPLOY_TOOLS = [
  { name: "Railway", flag: "--railway", desc: "Full-stack with databases" },
  { name: "Netlify", flag: "--netlify", desc: "Static sites & edge functions" },
  { name: "Vercel", flag: "--vercel", desc: "Frontend deployment platform" },
] as const;

export const NPM_TOOLS = [
  { name: "Typescript", flag: "--typescript", desc: "JavaScript with types" },
  { name: "Nestjs", flag: "--nestjs", desc: "Progressive Node.js framework" },
  { name: "Prettier", flag: "--prettier", desc: "Code formatter" },
  { name: "Live Server", flag: "--live-server", desc: "Server with live reload" },
  { name: "Localtunnel", flag: "--localtunnel", desc: "Public tunnels for localhost" },
  { name: "Vercel", flag: "--vercel", desc: "Deploy to Vercel" },
  { name: "Markserv", flag: "--markserv", desc: "Markdown server" },
  { name: "Psqlformat", flag: "--psqlformat", desc: "SQL formatter" },
  { name: "Ncu", flag: "--ncu", desc: "Check package updates" },
  { name: "Turbopack", flag: "--turbopack", desc: "Extremely fast Rust bundler" },
  { name: "Ngrok", flag: "--ngrok", desc: "Public tunnels for localhost" },
] as const;

export const SHELL_TOOLS = [
  { name: "Powerlevel10k", flag: "--powerlevel10k", desc: "Fastest and most beautiful ZSH theme" },
  { name: "Zsh Defer", flag: "--zsh-defer", desc: "Async plugin loading" },
  { name: "Zsh Autosuggestions", flag: "--zsh-autosuggestions", desc: "Fish-style autocomplete" },
  { name: "Zsh Syntax Highlighting", flag: "--zsh-syntax-highlighting", desc: "Syntax highlighting in commands" },
  { name: "History Substring", flag: "--history-substring", desc: "Fish-style history search" },
  { name: "Zsh Completions", flag: "--zsh-completions", desc: "Extra completion definitions" },
  { name: "Fzf Tab", flag: "--fzf-tab", desc: "Fuzzy tab completion with fzf" },
  { name: "You Should Use", flag: "--you-should-use", desc: "Reminds you of existing aliases" },
  { name: "Zsh Autopair", flag: "--zsh-autopair", desc: "Auto-close brackets and quotes" },
  { name: "Better Npm", flag: "--better-npm", desc: "Improved npm completion" },
] as const;

export const UI_TOOLS = [
  { name: "Font", flag: "--font", desc: "Font with ligatures and icons" },
  { name: "Extra Keys", flag: "--extra-keys", desc: "Additional keys on Termux keyboard" },
  { name: "Cursor", flag: "--cursor", desc: "Styled cursor with gradient" },
  { name: "Banner", flag: "--banner", desc: "ASCII banner with metallic effect on startup" },
] as const;

export const GAMES_TOOLS = [
  { name: "Buzz", flag: "--buzz", desc: "Quiz game with multiple categories" },
  { name: "Ctfgod", flag: "--ctfgod", desc: "Capture The Flag challenge solver" },
  { name: "Detective", flag: "--detective", desc: "Mystery investigation game" },
  { name: "Pet Friends", flag: "--pet-friends", desc: "Virtual pet simulator" },
  { name: "Tamagotchi", flag: "--tamagotchi", desc: "Retro digital pet" },
  { name: "Arcade", flag: "--arcade", desc: "Classic arcade games in terminal" },
] as const;


export const CATALOG_COUNTS = {
  ai: AI_TOOLS.length,
  dev: DEV_TOOLS.length,
  network: NETWORK_TOOLS.length,
  utils: UTILS_TOOLS.length,
  osint: OSINT_TOOLS.length,
  lang: LANG_TOOLS.length,
  db: DB_TOOLS.length,
  editor: EDITOR_TOOLS.length,
  auto: AUTO_TOOLS.length,
  deploy: DEPLOY_TOOLS.length,
  npm: NPM_TOOLS.length,
  shell: SHELL_TOOLS.length,
  ui: UI_TOOLS.length,
  games: GAMES_TOOLS.length,
} as const;
